#title in header
title: "Agate Mackerel ."

#main info
owner: "blog of agateMackerel"
email: 
info: ""
#description
desc: ""

#menu
menu:
#  Works: /Works
  ä¸»é¡µ: /
  æ ‡ç­¾: /tags
  å…³äº: /about
  å½’æ¡£: /archives
  
#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# Sidebar Avatar
avatar:
  # Replace the default image and set the url here.
  url: /images/avatar.gif   #å›¾ç‰‡çš„ä½ç½®ï¼Œä¹Ÿå¯ä»¥æ˜¯http://xxx.com/avatar.png
  # If true, the avatar will be dispalyed in circle.
  rounded: true   #å¤´åƒå±•ç¤ºåœ¨åœˆé‡Œ
  # If true, the avatar will be rotated with the cursor.
  rotated: false  #å¤´åƒéšå…‰æ ‡æ—‹è½¬
  
footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2022-08-13 16:42   #å»ºç«™æ—¶é—´


# Misc
#nanobar: /js/nanobar.min.js
#switch_light: â˜€ï¸
#switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png


article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
